/**
 * Mapping between ePAUTA course slugs and open-notebook Notebook IDs.
 *
 * The mapping is generated by `scripts/bootstrap_epauta_notebooks.py` in the
 * open-notebook repo and committed here as a stable configuration file.
 *
 * A slug has the form `<programa>/<CODIGO>` (e.g. `eit/CIT-1010`).
 */

import notebookMapping from "../data/notebook_mapping.json";

const mapping = notebookMapping as Record<string, string>;

/**
 * Return the open-notebook Notebook ID for a given slug, or `undefined`
 * if the slug is not mapped (or mapped to an empty string placeholder).
 */
export function getNotebookId(
  carrera: string,
  codigo: string,
): string | undefined {
  const slug = `${carrera}/${codigo}`;
  const id = mapping[slug];
  return id || undefined;
}

/**
 * Return a flat slug for convenience.
 */
export function getNotebookIdBySlug(slug: string): string | undefined {
  const id = mapping[slug];
  return id || undefined;
}

/**
 * Return all slugs that have a non-empty notebook ID.
 */
export function getMappedSlugs(): string[] {
  return Object.entries(mapping)
    .filter(([key, val]) => val && !key.startsWith("_"))
    .map(([key]) => key);
}
